#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Bundle HelixScreen installer into a single file for curl|sh usage
#
# Usage:
#   ./bundle-installer.sh > install.sh
#   ./bundle-installer.sh -o install.sh
#

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LIB_DIR="$SCRIPT_DIR/lib/installer"
OUTPUT_FILE=""

# Parse arguments
while [ $# -gt 0 ]; do
    case "$1" in
        -o|--output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        -h|--help)
            echo "Usage: $0 [-o output_file]"
            echo ""
            echo "Bundles the modular installer into a single file."
            echo "If no output file specified, writes to stdout."
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

# Generate the bundled installer
generate_bundle() {
    # Header
    cat << 'HEADER'
#!/bin/sh
# Copyright (C) 2025-2026 356C LLC
# SPDX-License-Identifier: GPL-3.0-or-later
#
# HelixScreen Installer
# This file is auto-generated by bundle-installer.sh
#
# Usage:
#   curl -sSL https://raw.githubusercontent.com/prestonbrown/helixscreen/main/scripts/install.sh | sh
#
# Or download and run:
#   wget https://raw.githubusercontent.com/prestonbrown/helixscreen/main/scripts/install.sh
#   chmod +x install.sh
#   ./install.sh
#
# Options:
#   --update    Update existing installation (preserves config)
#   --uninstall Remove HelixScreen
#   --clean     Remove old installation completely before installing (no config backup)
#   --version   Specify version (default: latest)
#

# Mark as bundled installer (modules check this to skip sourcing)
_HELIX_BUNDLED_INSTALLER=1

# Fail fast on any error
set -eu

# Configuration
GITHUB_REPO="prestonbrown/helixscreen"
SERVICE_NAME="helixscreen"

HEADER

    # Include each module (skip shebang and source guards)
    for module in common.sh platform.sh permissions.sh requirements.sh forgex.sh competing_uis.sh release.sh service.sh moonraker.sh uninstall.sh; do
        module_path="$LIB_DIR/$module"
        if [ ! -f "$module_path" ]; then
            echo "ERROR: Module not found: $module_path" >&2
            exit 1
        fi

        echo ""
        echo "# ============================================"
        echo "# Module: $module"
        echo "# ============================================"
        echo ""

        # Skip shebang, SPDX header, and source guard lines
        # Keep everything else
        awk '
            # Skip shebang
            /^#!/ { next }
            # Skip SPDX header
            /^# SPDX-License-Identifier:/ { next }
            # Skip module comment block at top (first few lines starting with #)
            NR <= 10 && /^# / { next }
            # Skip source guard
            /^\[ -n "\${_HELIX_.*_SOURCED:-}"/ { next }
            /_HELIX_.*_SOURCED=1/ { next }
            # Skip empty lines at the start
            NR <= 15 && /^$/ { next }
            # Print everything else
            { print }
        ' "$module_path"
    done

    # Include the main orchestration code
    cat << 'MAIN'

# ============================================
# Main orchestration
# ============================================

# Set up error trap (ERR is bash-specific, skip on POSIX shells like dash/ash)
# shellcheck disable=SC3047
trap 'error_handler $LINENO' ERR 2>/dev/null || true

# Print usage
usage() {
    echo "HelixScreen Installer"
    echo ""
    echo "Usage: $0 [options]"
    echo ""
    echo "Options:"
    echo "  --update       Update existing installation (preserves config)"
    echo "  --uninstall    Remove HelixScreen"
    echo "  --clean        Clean install: remove old installation completely,"
    echo "                 including config and caches (asks for confirmation)"
    echo "  --version VER  Install specific version (default: latest)"
    echo "  --local FILE   Install from local tarball (skip download)"
    echo "  --help         Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0                    # Fresh install, latest version"
    echo "  $0 --update           # Update existing installation"
    echo "  $0 --clean            # Remove old install completely, then install"
    echo "  $0 --version v1.1.0   # Install specific version"
    echo "  $0 --local /tmp/helixscreen-ad5m.tar.gz  # Install from local file"
}

# Configure platform-specific settings before stopping competing UIs
# (ForgeX display mode, stock UI disable, screen.sh patching)
configure_platform() {
    case "$AD5M_FIRMWARE" in
        forge_x)
            configure_forgex_display || true
            disable_stock_firmware_ui || true
            patch_forgex_screen_sh || true
            patch_forgex_screen_drawing || true
            install_forgex_logged_wrapper || true
            ;;
        klipper_mod)
            # Klipper Mod-specific install-time configuration (if any)
            ;;
    esac
}

# Deploy platform-specific hooks for the init script
# Must be called after extract_release (hooks are in the release package)
install_platform_hooks() {
    local platform_hook=""
    case "$AD5M_FIRMWARE" in
        forge_x)     platform_hook="ad5m-forgex" ;;
        klipper_mod) platform_hook="ad5m-kmod" ;;
    esac

    # Pi and K1 platform hooks
    if [ "$platform" = "pi" ]; then
        platform_hook="pi"
    elif [ "$platform" = "k1" ]; then
        platform_hook="k1"
    fi

    if [ -n "$platform_hook" ]; then
        deploy_platform_hooks "$INSTALL_DIR" "$platform_hook"
    fi
}

# Main installation flow
main() {
    update_mode=false
    uninstall_mode=false
    clean_mode=false
    version=""
    local_tarball=""

    # Parse arguments
    while [ $# -gt 0 ]; do
        case $1 in
            --update)
                update_mode=true
                shift
                ;;
            --uninstall)
                uninstall_mode=true
                shift
                ;;
            --clean)
                clean_mode=true
                shift
                ;;
            --version)
                if [ -z "${2:-}" ]; then
                    log_error "--version requires a version argument"
                    exit 1
                fi
                version="$2"
                shift 2
                ;;
            --local)
                if [ -z "${2:-}" ]; then
                    log_error "--local requires a file path argument"
                    exit 1
                fi
                local_tarball="$2"
                shift 2
                ;;
            --help|-h)
                usage
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                usage
                exit 1
                ;;
        esac
    done

    echo ""
    echo "${BOLD}========================================${NC}"
    echo "${BOLD}       HelixScreen Installer${NC}"
    echo "${BOLD}========================================${NC}"
    echo ""

    # Detect platform
    platform=$(detect_platform)
    log_info "Detected platform: ${BOLD}${platform}${NC}"

    if [ "$platform" = "unsupported" ]; then
        log_error "Unsupported platform: $(uname -m)"
        log_error "HelixScreen supports:"
        log_error "  - Raspberry Pi (aarch64/armv7l)"
        log_error "  - FlashForge Adventurer 5M (armv7l)"
        log_error "  - Creality K1 series with Simple AF"
        exit 1
    fi

    # For AD5M/K1, detect firmware variant and set appropriate paths
    local firmware=""
    if [ "$platform" = "ad5m" ]; then
        AD5M_FIRMWARE=$(detect_ad5m_firmware)
        firmware="$AD5M_FIRMWARE"
    elif [ "$platform" = "k1" ]; then
        K1_FIRMWARE=$(detect_k1_firmware)
        firmware="$K1_FIRMWARE"
    fi
    set_install_paths "$platform" "$firmware"

    # Check permissions
    check_permissions "$platform"

    # Handle uninstall (doesn't need all checks)
    if [ "$uninstall_mode" = true ]; then
        uninstall "$platform"
        exit 0
    fi

    # Pre-flight checks
    log_info "Running pre-flight checks..."
    check_requirements
    install_runtime_deps "$platform"
    check_disk_space "$platform"
    detect_init_system

    # Get version (skip if using local tarball)
    if [ -n "$local_tarball" ]; then
        # Validate local file exists
        if [ ! -f "$local_tarball" ]; then
            log_error "Local tarball not found: $local_tarball"
            exit 1
        fi
        # Extract version from filename if possible (helixscreen-platform-v1.2.3.tar.gz)
        version=$(echo "$local_tarball" | sed -n 's/.*helixscreen-[^-]*-\(v[0-9.]*\)\.tar\.gz/\1/p')
        if [ -z "$version" ]; then
            version="local"
        fi
        log_info "Installing from local file: ${BOLD}${local_tarball}${NC}"
    else
        if [ -z "$version" ]; then
            version=$(get_latest_version "$platform")
        fi
    fi
    log_info "Target version: ${BOLD}${version}${NC}"

    # Configure platform-specific settings before stopping UIs
    configure_platform

    # Stop competing UIs
    stop_competing_uis

    # Clean old installation if requested
    if [ "$clean_mode" = true ]; then
        clean_old_installation "$platform"
    fi

    # Stop existing service if updating
    if [ "$update_mode" = true ]; then
        if [ ! -d "$INSTALL_DIR" ]; then
            log_warn "No existing installation found. Performing fresh install."
        fi
        stop_service
    fi

    # Download and install (or use local tarball)
    if [ -n "$local_tarball" ]; then
        use_local_tarball "$local_tarball"
    else
        download_release "$version" "$platform"
    fi
    extract_release "$platform"
    fix_install_ownership
    install_service "$platform"
    install_platform_hooks

    # Configure Moonraker update_manager (Pi only - enables web UI updates)
    configure_moonraker_updates "$platform"

    # Start service
    start_service

    # Cleanup on success
    cleanup_on_success

    echo ""
    echo "${GREEN}${BOLD}========================================${NC}"
    echo "${GREEN}${BOLD}    Installation Complete!${NC}"
    echo "${GREEN}${BOLD}========================================${NC}"
    echo ""
    echo "HelixScreen ${version} installed to ${INSTALL_DIR}"
    echo ""
    print_post_install_commands
    echo ""

    if [ "$platform" = "ad5m" ] || [ "$platform" = "k1" ]; then
        echo "Note: You may need to reboot for the display to update."
    fi
}

# Run main
main "$@"
MAIN
}

# Output to file or stdout
if [ -n "$OUTPUT_FILE" ]; then
    generate_bundle > "$OUTPUT_FILE"
    chmod +x "$OUTPUT_FILE"
    echo "Generated: $OUTPUT_FILE"
    echo "Size: $(wc -c < "$OUTPUT_FILE" | tr -d ' ') bytes"
else
    generate_bundle
fi
